#index:
#    path: /admin
#    controller: App\Controller\DefaultController::index
controllers:
  resource: '../src/Controller/'
  type: annotation
home:
  path: /
  controller: App\Controller\DashboardController::index